language: go
go:
  - "1.10"
before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo  apt-get install -y nodejs
  - sudo npm install -g npm
script:
  - make go-get
  - bash <(curl -s https://codecov.io/bash) -cF go
  - ./build/ci.sh
  - make pi
  - bundle install
  - env
  - /usr/bin/npm install
  - ./node_modules/.bin/webpack -d
  - ./node_modules/.bin/standard jsx/*
  - npm test
  - bash <(curl -s https://codecov.io/bash) -cF javascript
  - make clean
  - make deb
