language: go
dist: trusty
go:
  - "1.6"
node_js:
  - "6"
script:
  - make go-get
  - make test
  - env GOARCH=arm make bin
  - bundle install
  - npm install
  - webpack -d
  - standard jsx/*
  - make deb
