language: go
sudo: required
dist: trusty
go:
  - "1.9"
script:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo ln -sf /usr/bin/nodejs /usr/bin/node
  - sudo npm install -g npm
  - make go-get
  - make test
  - env GOARCH=arm make bin
  - bundle install
  - env
  - /usr/bin/npm install
  - ./node_modules/.bin/webpack -d
  - ./node_modules/.bin/standard jsx/*
  - make deb
