language: go
dist: trusty
sudo: required
go:
  - "1.6"
node_js:
  - "6"
script:
  - sudo apt-get remove node -y --purge
  - sudo apt-get install nodejs -y
  - sudo ln -sf /usr/bin/nodejs /usr/bin/node
  - make go-get
  - make test
  - env GOARCH=arm make bin
  - bundle install
  - npm install
  - ./node_modules/.bin/webpack -d
  - ./node_modules/.bin/standard jsx/*
  - make deb
