matrix:
  include:
    - language: go
      go:
        - "1.13"
      before_install:
        - sudo  apt-get install -y libasound2-dev
      script:
        - ./build/ci.sh
        - bash <(curl -s https://codecov.io/bash) -cF go
        - make pi
        - bundle install
        - make clean
        - make go
        - make deb

    - language: node_js
      node_js: 
        - "lts/*"
      install:
        - npm install
      script:
        - make build-ui        
        - npm run js-lint
        - make sass-lint
        - npm test
        - bash <(curl -s https://codecov.io/bash) -cF javascript 
