language: go
dist: trusty
go:
  - "1.9"
script:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - apt-get install -y nodejs
  - ln -sf /usr/bin/nodejs /usr/bin/node
  - npm install -g npm
  - make go-get
  - make test
  - make pi
  - bundle install
  - env
  - /usr/bin/npm install
  - ./node_modules/.bin/webpack -d
  - ./node_modules/.bin/standard jsx/*
  - make deb
