matrix:
  include:
    - language: go
      go:
        - "1.13"
      before_install:
        - sudo apt-get install -y libasound2-dev
        - nvm use node
      install:
        - npm ci
      script:
        - ./build/ci.sh
        - bash <(curl -s https://codecov.io/bash) -cF go
        - make pi
        - bundle install
        - make clean
        - make go
        - make deb

    - language: node_js
      node_js:
        - "lts/*"
      install:
        - npm ci
      script:
        - npm run build
        - npm run js-lint
        - npm run sass-lint
        - npm test
        - bash <(curl -s https://codecov.io/bash) -cF javascript
