[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.2"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/kidoman/embd"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  branch = "master"
  name = "github.com/reef-pi/adafruitio"

[[constraint]]
  branch = "master"
  name = "github.com/reef-pi/drivers"

[[constraint]]
  branch = "master"
  name = "github.com/reef-pi/hal"

[[constraint]]
  branch = "master"
  name = "github.com/reef-pi/rpi"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.19.2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/robfig/cron.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[override]]
  name = "github.com/PaulSRock/kasalink"
  branch = "test"
  source = "https://github.com/theatrus/kasalink"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  branch = "master"
  name = "golang.org/x/sys"
