---
controller:
  enable_gpio: true
  enable_pwm: false
  enable_adc: false
  enable_temperature_sensor: false
  database: "reef-pi.db"
  outlets:
    AC1:
      pin: 12
    AC2:
      pin: 13
    DC10:
      pin: 12
      type: pwm
api:
  address: "localhost:8080"
  enable_auth: false
  auth:
    id: 35adsjfaksjfdhks5eun435b.apps.googleusercontent.com
    secret: adqwieuqiwue
    callback_url: http://localhost:8088/auth/callback/google
    domain: example.com
    users:
      - foobar
    gomni_auth_secret: sadfhsadfkh238asdf
  dsi_display: false
  image_directory: /var/lib/reef-pi/images
  interface: eth0
