name: go
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: codecov/codecov-action@v1
      - run: make install
      - run: make vet
      - run: make imports
      - run: make race
