name: smoke
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
      - run: make install
      - run: make go
      - run: make ui
      - run: |
          make start-dev &
          make smoke
