name: translation
on: [push, pull_request]

jobs:
  Translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 11.12
        uses: actions/setup-node@v1
        with:
          node-version: 11.12
      - uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: npm i
      - name: Check Translations
        run: npm run translations:chk
