name: Check translation status
on: [push, pull_request]

jobs:
  Translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.0
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-10-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-10-node_modules-
      - name: Install
        run: npm i
      - name: Check Translations
        run: npm run translations:chk
